import {
  MAX_MERGED_ITEMS,
  MERGED_REPORT_WORD_BUDGET,
  SECTION_ORDER,
  WEEKLY_TOPIC_KEYS,
  buildWeeklyDigest,
  countWords,
  generateStructuredReport,
} from '@compass/analysis';
import { instantFromIso, previousCivilDayWindow, type Instant } from '@compass/clock';
import { ingestRunRowId, type CompassDatabase, type ScopedDb } from '@compass/db';
import { createMigratedTestDatabase, type TestDatabase } from '@compass/db/testing';
import { KnowledgeStore, buildKnowledgeSnapshot, provisionRoster } from '@compass/knowledge-model';
import { ensureMergedReport, ensureWeeklyDigest } from '@compass/pipeline';
import { SeedConnector, loadSeedFixtures, resolveSeededRun, seedBundle } from '@compass/seed-connector';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { SEED_TIMEZONE, rosterFromFixtures } from '../src/bootstrap.js';

/**
 * The merged report and the weekly digest, over the **seeded three-team organization**, through the real
 * pipeline and a real migrated PostgreSQL 17.
 *
 * The unit tests in `packages/analysis` and `packages/renderers` prove the ranking and the budget against
 * constructed inputs. This is the acceptance criterion's own wording: *a test asserts the budget on the
 * seeded three-team org*. Nothing here is a fixture — every report is generated by `ensureMergedReport`,
 * which calls the same `ensureDailyReport` the worker's scheduled job calls.
 */

/**
 * The three seeded teams, read from the fixtures rather than hard-coded.
 *
 * A literal list would pass for as long as the fixture happened to name those three and would then fail
 * as a mysterious "zero findings" rather than as "that team does not exist" — which is exactly how the
 * first draft of this test failed.
 */
const seededTeamKeys = (): readonly string[] =>
  loadSeedFixtures()
    .organization.teams.map((team) => team.key)
    .sort();

let ORGANIZATION_ID: string;
let TEAM_KEYS: readonly string[];
let database: TestDatabase;
let run: ReturnType<typeof resolveSeededRun>;

const scoped = (): ScopedDb => database.scopedFor(ORGANIZATION_ID);

const pipelineRequest = (now: Instant) => {
  const connector = new SeedConnector(run.dataset);
  return {
    organizationId: ORGANIZATION_ID,
    now,
    timezone: run.timezone,
    ingestWindow: run.ingestWindow,
    runId: ingestRunRowId(ORGANIZATION_ID, connector.connectorId, run.ingestWindow.start, run.ingestWindow.end, 1),
    connector,
    database: database.db as CompassDatabase,
    // No narrator: the merged report is never narrated by design, and the per-team reports underneath it
    // are the deterministic render here, which is what makes the byte-identity assertions below mean
    // something.
    narrator: null,
  };
};

beforeAll(async () => {
  // The same instant the cold-start test uses: the one day `seed/MANIFEST.md` designs a single report
  // around, and the day a reviewer actually lands on once the host clock passes the seeded span.
  const bundle = seedBundle();
  run = resolveSeededRun({ hostNow: instantFromIso('2026-07-31T07:15:00Z'), env: {} });
  ORGANIZATION_ID = bundle.organizationId;
  TEAM_KEYS = seededTeamKeys();

  database = await createMigratedTestDatabase({
    organizationId: ORGANIZATION_ID,
    name: 'Northwind Systems',
    slug: 'northwind-merged',
    timezone: SEED_TIMEZONE,
    at: new Date(bundle.window.start),
  });

  // The roster is *declared configuration*, not an observation, so ingest never creates it — and without
  // it every per-team scope resolves to no projects and every report is six honest absences. That is how
  // this test first failed: three reports, six sections each, zero findings. `bootstrap()` provisions the
  // same rows on a real boot.
  const store = new KnowledgeStore(scoped());
  await provisionRoster(store, rosterFromFixtures(loadSeedFixtures(), SEED_TIMEZONE, bundle.window.start));
}, 240_000);

afterAll(async () => {
  await database?.close();
});

describe('the merged report over the seeded three-team organization', () => {
  it('generates all three teams through the real pipeline and merges them', async () => {
    const merged = await ensureMergedReport({ ...pipelineRequest(run.now), teamKeys: TEAM_KEYS });

    expect(merged.teamReports.map((entry) => entry.teamKey)).toEqual([...TEAM_KEYS].sort());
    // Real rows, with real ids — not a computed object standing in for one.
    for (const entry of merged.teamReports) {
      expect(entry.bundle.report.id.length, entry.teamKey).toBeGreaterThan(0);
      expect(entry.bundle.sections).toHaveLength(SECTION_ORDER.length);
    }
  }, 240_000);

  it('never exceeds the 400 words documented in docs/budgets.md', async () => {
    const { rendered } = await ensureMergedReport({ ...pipelineRequest(run.now), teamKeys: TEAM_KEYS });

    expect(rendered.wordBudget).toBe(MERGED_REPORT_WORD_BUDGET);
    expect(rendered.wordCount).toBeLessThanOrEqual(MERGED_REPORT_WORD_BUDGET);
    expect(countWords(rendered.prose)).toBe(rendered.wordCount);
  }, 240_000);

  it('is a ranked index rather than three reports concatenated', async () => {
    const { merged, rendered } = await ensureMergedReport({ ...pipelineRequest(run.now), teamKeys: TEAM_KEYS });

    const lines = rendered.sections.flatMap((section) => section.lines);
    expect(lines.length).toBeLessThanOrEqual(MAX_MERGED_ITEMS);

    // Ranked, and strictly so: the scores are non-increasing down the page.
    const scores = merged.items.map((item) => item.impact.score);
    expect([...scores].sort((left, right) => right - left)).toEqual(scores);

    // A concatenation would carry every team's every finding. This carries a fraction of them, and says so.
    const totalFindings = merged.teams.reduce((sum, team) => sum + team.itemCount, 0);
    expect(totalFindings).toBeGreaterThan(merged.items.length);

    // The omitted count is in *conditions*, not occurrences: an entity two teams both see is one finding,
    // deduped before the cut, so this is below the raw per-team total rather than equal to it.
    expect(merged.omittedItemCount).toBeGreaterThan(0);
    expect(merged.omittedItemCount).toBeLessThan(totalFindings - merged.items.length + 1);
    expect(rendered.omittedLine).toContain(String(merged.omittedItemCount));
  }, 240_000);

  it('links every merged item to a real per-team report item by its stable id', async () => {
    const { merged, teamReports } = await ensureMergedReport({ ...pipelineRequest(run.now), teamKeys: TEAM_KEYS });

    // The foreign key, resolved against the *stored* rows rather than against the payload it came from —
    // so this proves the link a reader would follow actually lands on a persisted claim.
    const teamsById = new Map<string, Set<string>>();
    for (const entry of teamReports) {
      for (const section of entry.bundle.sections) {
        for (const item of section.items) {
          const teams = teamsById.get(item.stableId) ?? new Set<string>();
          teams.add(entry.teamKey);
          teamsById.set(item.stableId, teams);
        }
      }
    }

    expect(merged.items.length).toBeGreaterThan(0);
    for (const item of merged.items) {
      expect(teamsById.has(item.stableId), `${item.teamKey}/${item.stableId}`).toBe(true);
      expect([...(teamsById.get(item.stableId) ?? [])], item.stableId).toContain(item.teamKey);
    }
  }, 240_000);

  it('gives no two teams the same *process* item id, so a dismissal cannot cross teams', async () => {
    /**
     * The bug class this closes, asserted where it was found.
     *
     * A stable id is derived from `(organization, entityRef, causeKind, discriminator)` and deliberately
     * *not* from the team: a ticket does not change identity when it is read from another scope. That is
     * right for an artifact, and it is why one objective two teams both serve legitimately appears in both
     * reports — which the merged report handles by keeping one line per condition.
     *
     * It is wrong for an item about a team's own **process**, where the entity *is* the team. Five
     * detectors used a literal there — `progress:process`, `team:calibration`, `team:technical_debt`,
     * `commit:unattributed` — so every team in one organization shared one id, a dismissal on one team's
     * velocity item suppressed all three, and the merged page could not attribute it. Those are keyed on
     * the scope now, and this is what stops the sixth appearing.
     */
    const { teamReports } = await ensureMergedReport({ ...pipelineRequest(run.now), teamKeys: TEAM_KEYS });

    const teamsById = new Map<string, { readonly teams: Set<string>; readonly sections: Set<string> }>();
    for (const entry of teamReports) {
      for (const section of entry.bundle.sections) {
        for (const item of section.items) {
          const found = teamsById.get(item.stableId) ?? { teams: new Set<string>(), sections: new Set<string>() };
          found.teams.add(entry.teamKey);
          found.sections.add(`${section.sectionKey}/${item.causeKind}`);
          teamsById.set(item.stableId, found);
        }
      }
    }

    // A process item is one whose cause is about the team rather than about an artifact. Those must never
    // be shared; an artifact-keyed item may be, and the merged report is what reconciles that.
    const processCauses = new Set([
      'sprint_completion',
      'projected_completion',
      'velocity',
      'kanban_flow',
      'estimation_noise',
      'technical_debt_growth',
      'unattributed',
    ]);

    const shared = [...teamsById.entries()]
      .filter(([, found]) => found.teams.size > 1)
      .filter(([, found]) => [...found.sections].some((entry) => processCauses.has(entry.split('/')[1] ?? '')))
      .map(([stableId, found]) => `${stableId} (${[...found.sections].join(', ')}) in ${[...found.teams].sort().join(' + ')}`);

    expect(
      shared,
      'these process item ids appear in more than one team’s report, so a dismissal on one would suppress the ' +
        'others and the merged report cannot attribute them',
    ).toEqual([]);
  }, 240_000);

  it('carries one line per condition, even when two teams can see it', async () => {
    // The other half: an artifact in two scopes is one finding, and the merged page must not spend its
    // budget saying it three times.
    const { merged } = await ensureMergedReport({ ...pipelineRequest(run.now), teamKeys: TEAM_KEYS });
    const ids = merged.items.map((item) => item.stableId);

    expect(new Set(ids).size).toBe(ids.length);
  }, 240_000);

  it('names each team’s own stored report, so the link down is to a specific report', async () => {
    const { merged, teamReports } = await ensureMergedReport({ ...pipelineRequest(run.now), teamKeys: TEAM_KEYS });
    const byTeam = new Map(teamReports.map((entry) => [entry.teamKey, entry.bundle.report.id]));

    for (const team of merged.teams) {
      expect(team.reportId, team.teamKey).toBe(byTeam.get(team.teamKey));
    }
  }, 240_000);

  it('does not depend on the order the teams were named in', async () => {
    const forwards = await ensureMergedReport({ ...pipelineRequest(run.now), teamKeys: TEAM_KEYS });
    const backwards = await ensureMergedReport({ ...pipelineRequest(run.now), teamKeys: [...TEAM_KEYS].reverse() });

    expect(backwards.rendered.text).toBe(forwards.rendered.text);
  }, 240_000);
});

describe('the weekly digest over the seeded organization', () => {
  it('carries all six topics with a named producer each', async () => {
    const { digest } = await ensureWeeklyDigest({ ...pipelineRequest(run.now), teamKey: 'platform' });

    // Pinned to the *number* the criterion names, not only to the constant: `toEqual([...KEYS])` would keep
    // passing if somebody removed a topic from the list, because the expectation moves with it.
    expect(WEEKLY_TOPIC_KEYS.length, 'the criterion names six documented topics').toBe(6);
    expect(digest.topics).toHaveLength(6);

    expect(digest.topics.map((topic) => topic.key)).toEqual([...WEEKLY_TOPIC_KEYS]);
    for (const topic of digest.topics) {
      expect(topic.producer.length, topic.key).toBeGreaterThan(0);
    }
  }, 240_000);

  it('renders as prose with no chart, canvas or svg', async () => {
    const { rendered } = await ensureWeeklyDigest({ ...pipelineRequest(run.now), teamKey: 'platform' });

    for (const token of ['<svg', '<canvas', '<img', 'chart', 'sparkline']) {
      expect(rendered.text.toLowerCase(), token).not.toContain(token);
    }
    expect(rendered.prose.length).toBeGreaterThan(0);
  }, 240_000);

  it('is deterministic for the same (organization, team, instant)', async () => {
    /**
     * Two calls agreeing is not enough on its own.
     *
     * `ensureWeeklyDigest` builds from `ensureDailyReport`, which *reads the stored row* on the second call
     * — so two identical answers could mean "deterministic" or merely "read the same row twice", and only
     * one of those is the criterion. The weaker reading is excluded by comparing against a digest built
     * from a **freshly materialised snapshot** for the same instant: a separate analysis run, over a
     * snapshot rebuilt from the knowledge model, reaching the same six topics.
     */
    const first = await ensureWeeklyDigest({ ...pipelineRequest(run.now), teamKey: 'platform' });
    const second = await ensureWeeklyDigest({ ...pipelineRequest(run.now), teamKey: 'platform' });

    expect(JSON.stringify(second.digest)).toBe(JSON.stringify(first.digest));
    expect(second.rendered.text).toBe(first.rendered.text);

    // The independent path: rebuild the snapshot, re-run the pure analysis, rebuild the digest.
    const store = new KnowledgeStore(scoped());
    const snapshot = await buildKnowledgeSnapshot(store, {
      scope: { kind: 'team', teamKey: 'platform' },
      instant: run.now,
      timezone: SEED_TIMEZONE,
      window: previousCivilDayWindow(run.now, SEED_TIMEZONE),
    });
    const fresh = buildWeeklyDigest({
      teamKey: 'platform',
      report: generateStructuredReport(snapshot, run.now, {
        deploySignalAvailable: false,
        coverage: [],
        maxItemsPerSection: 12,
      }),
    });

    // The topics, their states and their sentences — the whole payload bar the window, which is derived from
    // the same instant either way. Compared topic by topic so a failure names which one moved.
    expect(fresh.topics.map((topic) => topic.key)).toEqual(first.digest.topics.map((topic) => topic.key));
    for (const [index, topic] of fresh.topics.entries()) {
      const stored = first.digest.topics[index]!;
      expect(topic.state, topic.key).toBe(stored.state);
      expect(topic.producer, topic.key).toBe(stored.producer);
      expect(topic.statement, topic.key).toBe(stored.statement);
    }
    expect(fresh.summary).toBe(first.digest.summary);
    expect(fresh.undefinedTopicKeys).toEqual(first.digest.undefinedTopicKeys);
  }, 240_000);

  it('states which topics are undefined rather than emitting a number for them', async () => {
    const { digest } = await ensureWeeklyDigest({ ...pipelineRequest(run.now), teamKey: 'platform' });

    for (const topic of digest.topics) {
      if (topic.state !== 'undefined') continue;
      // No numeric field to format as a zero, and a sentence that says what is missing.
      expect(Object.keys(topic).sort()).toEqual(['key', 'producer', 'state', 'statement', 'title']);
      expect(topic.statement.length).toBeGreaterThan(20);
      expect(digest.undefinedTopicKeys).toContain(topic.key);
    }
  }, 240_000);
});

describe('the archive holds what the pipeline wrote', () => {
  it('lists every generated report with its scope, date and fallback flag', async () => {
    await ensureMergedReport({ ...pipelineRequest(run.now), teamKeys: TEAM_KEYS });

    const { listReportArchive } = await import('@compass/db');
    const entries = await listReportArchive(scoped());

    expect(entries.length).toBeGreaterThanOrEqual(TEAM_KEYS.length);
    for (const entry of entries) {
      expect(entry.reportDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(['team', 'merged']).toContain(entry.scopeKind);
      // No narrator was configured, so nothing was attempted and nothing degraded.
      expect(entry.fallbackRenderer).toBe(false);
      expect(entry.rendererId).toBe('template');
    }
  }, 240_000);

  it('is ordered newest first, with a deterministic tiebreak within a date', async () => {
    const { listReportArchive } = await import('@compass/db');
    const entries = await listReportArchive(scoped());

    for (let index = 1; index < entries.length; index += 1) {
      const previous = entries[index - 1]!;
      const current = entries[index]!;
      expect(previous.reportInstant >= current.reportInstant).toBe(true);
      if (previous.reportInstant === current.reportInstant) {
        expect(`${previous.scopeKind}:${previous.scopeKey}` <= `${current.scopeKind}:${current.scopeKey}`).toBe(true);
      }
    }
  }, 240_000);
});
