import { createSign, generateKeyPairSync } from 'node:crypto';

import {
  XmlParseError,
  attributeValue,
  canonicalizeExclusive,
  childNamed,
  findElementsById,
  parseXml,
  textOf,
  verifyXmlSignature,
  type XmlElement,
} from '@compass/auth';
import { describe, expect, it } from 'vitest';

/**
 * The XML reader, the exclusive canonicaliser and the signature verifier.
 *
 * ## What this file can and cannot prove
 *
 * Stated plainly, because it changes how the results should be read.
 *
 * **It cannot prove interoperability.** The signatures below are produced by signing this module's own
 * canonical output, so a canonicaliser that disagreed with the world in some corner would still pass
 * every "valid signature verifies" case here. Proving interoperability needs an assertion produced by
 * a real identity provider, which is an integration test against a live IdP and not something a unit
 * suite can fake — a fixture generated by this code would be exactly as circular.
 *
 * What makes that acceptable is the *direction* the failure falls. A canonicaliser that differs from
 * an IdP produces a digest mismatch, which is a refusal: SAML sign-in stops working and says why. It
 * does not admit anybody. The dangerous direction — accepting an assertion that should be refused —
 * is what the rest of this file is about, and those cases are not circular at all.
 *
 * **It does prove the refusals**, each one independently:
 *
 *  - a tampered assertion is refused even though its signature is intact (`digest_mismatch`);
 *  - a signature over a *different* element cannot vouch for this one (`reference_mismatch`);
 *  - a duplicated id is refused outright, which is the XML signature wrapping attack;
 *  - a signature moved out of the element it signs is refused (`signature_not_enveloped`);
 *  - SHA-1, inclusive c14n and unknown transforms are refused rather than accommodated;
 *  - a DOCTYPE, an entity, a comment and a CDATA section are all parse failures.
 *
 * **And it pins the canonical form** on cases where the exclusive-c14n rules are unambiguous, which is
 * what would catch a careless edit to the canonicaliser: unused namespaces dropped, attributes sorted
 * by namespace then local name, declarations emitted only on change, empty elements written open-close.
 */

// ---------------------------------------------------------------------------
// The reader's refusals
// ---------------------------------------------------------------------------

describe('the XML reader refuses what a canonicaliser cannot safely handle', () => {
  it('refuses a DOCTYPE, which is the external-entity door', () => {
    expect(() => parseXml('<!DOCTYPE foo><foo/>')).toThrow(XmlParseError);
    expect(() => parseXml('<!DOCTYPE foo><foo/>')).toThrow(/DOCTYPE/i);
  });

  it('refuses an entity declaration, which is billion-laughs', () => {
    expect(() =>
      parseXml('<!DOCTYPE x [<!ENTITY a "aaaa">]><x>&a;</x>'),
    ).toThrow(XmlParseError);
  });

  it('refuses an undeclared entity reference rather than passing it through as text', () => {
    // Passing it through would mean the digest covers different bytes than a reader sees.
    expect(() => parseXml('<x>&custom;</x>')).toThrow(/predefined/i);
  });

  it('resolves the five predefined entities and numeric character references', () => {
    expect(textOf(parseXml('<x>&lt;&amp;&gt;&quot;&apos;</x>'))).toBe('<&>"\'');
    expect(textOf(parseXml('<x>&#65;&#x42;</x>'))).toBe('AB');
  });

  it('refuses comments, because with/without-comments c14n is a wrapping vector', () => {
    expect(() => parseXml('<x><!-- hello --></x>')).toThrow(/comment/i);
  });

  it('refuses CDATA sections', () => {
    expect(() => parseXml('<x><![CDATA[raw]]></x>')).toThrow(/CDATA/i);
  });

  it('refuses a processing instruction that is not the XML declaration', () => {
    expect(() => parseXml('<?xml version="1.0"?><x/>')).not.toThrow();
    expect(() => parseXml('<?php evil ?><x/>')).toThrow(/processing instruction/i);
  });

  it('refuses an unbound prefix rather than inventing a namespace for it', () => {
    expect(() => parseXml('<a:x/>')).toThrow(/not bound/i);
  });

  it('refuses mismatched and unclosed tags', () => {
    expect(() => parseXml('<a><b></a></b>')).toThrow(XmlParseError);
    expect(() => parseXml('<a><b></b>')).toThrow(/never closed/i);
  });

  it('refuses a duplicated attribute', () => {
    expect(() => parseXml('<a x="1" x="2"/>')).toThrow(/twice/i);
  });

  it('keeps `>` inside an attribute value as data rather than ending the tag there', () => {
    const element = parseXml('<a note="1 > 0"><b/></a>');
    expect(attributeValue(element, 'note')).toBe('1 > 0');
    expect(element.children).toHaveLength(1);
  });

  it('builds one tree, so a child appended after the parent is visible from the root', () => {
    // A regression guard for the copy-versus-identity trap: spreading an element into the parent's
    // child list makes a copy, and children appended later would land on the copy.
    const root = parseXml('<a><b><c>deep</c></b></a>');
    const b = childNamed(root, '', 'b');
    expect(b).not.toBeNull();
    expect(textOf(root)).toBe('deep');
    expect(childNamed(b as XmlElement, '', 'c')).not.toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Exclusive canonicalisation
// ---------------------------------------------------------------------------

describe('exclusive canonicalisation', () => {
  it('drops a namespace declaration nothing visibly uses', () => {
    // The defining property of *exclusive* c14n, and the reason IdPs use it: `unused` is declared and
    // referenced by nothing, so it does not appear.
    const canonical = canonicalizeExclusive(parseXml('<a:Foo xmlns:a="urn:a" xmlns:unused="urn:u"/>'));
    expect(canonical).toBe('<a:Foo xmlns:a="urn:a"></a:Foo>');
  });

  it('keeps a namespace a prefixed attribute uses', () => {
    const canonical = canonicalizeExclusive(parseXml('<Foo xmlns:a="urn:a" a:x="1"/>'));
    expect(canonical).toBe('<Foo xmlns:a="urn:a" a:x="1"></Foo>');
  });

  it('does not emit the default namespace for an unprefixed attribute', () => {
    // An unprefixed attribute is in *no* namespace, so the default declaration is not visibly used
    // by it. This is the subtlety that separates exclusive from inclusive c14n.
    const canonical = canonicalizeExclusive(parseXml('<a:Foo xmlns:a="urn:a" xmlns="urn:d" bare="1"/>'));
    expect(canonical).toBe('<a:Foo xmlns:a="urn:a" bare="1"></a:Foo>');
  });

  it('writes an empty element open-and-close, never self-closed', () => {
    expect(canonicalizeExclusive(parseXml('<a/>'))).toBe('<a></a>');
  });

  it('sorts attributes by namespace URI then local name, unprefixed first', () => {
    const canonical = canonicalizeExclusive(
      parseXml('<Foo xmlns:z="urn:z" xmlns:a="urn:a" z:b="1" a:c="2" second="3" first="4"/>'),
    );
    // Unprefixed attributes are in no namespace (empty URI) so they sort first, alphabetically;
    // then urn:a, then urn:z.
    expect(canonical).toBe(
      '<Foo xmlns:a="urn:a" xmlns:z="urn:z" first="4" second="3" a:c="2" z:b="1"></Foo>',
    );
  });

  it('sorts namespace declarations by prefix', () => {
    const canonical = canonicalizeExclusive(parseXml('<Foo xmlns:z="urn:z" xmlns:a="urn:a" z:x="1" a:y="2"/>'));
    expect(canonical.indexOf('xmlns:a')).toBeLessThan(canonical.indexOf('xmlns:z'));
  });

  it('emits a declaration only where it changes, not on every descendant', () => {
    const canonical = canonicalizeExclusive(parseXml('<a:x xmlns:a="urn:a"><a:y><a:z/></a:y></a:x>'));
    expect(canonical).toBe('<a:x xmlns:a="urn:a"><a:y><a:z></a:z></a:y></a:x>');
  });

  it('re-emits a declaration when a descendant rebinds the prefix', () => {
    const canonical = canonicalizeExclusive(parseXml('<a:x xmlns:a="urn:a"><a:y xmlns:a="urn:b"/></a:x>'));
    expect(canonical).toBe('<a:x xmlns:a="urn:a"><a:y xmlns:a="urn:b"></a:y></a:x>');
  });

  it('escapes text and attribute values by the c14n rules, which differ from each other', () => {
    // `>` is escaped in text and left alone in attributes; `"` is escaped in attributes only;
    // tab and newline are escaped in attributes and preserved in text.
    const canonical = canonicalizeExclusive(parseXml('<a v="x&quot;y&#x9;z">1 &lt; 2 &amp; 3 &gt; 0</a>'));
    expect(canonical).toBe('<a v="x&quot;y&#x9;z">1 &lt; 2 &amp; 3 &gt; 0</a>');
  });

  it('canonicalises a subtree in its own right, inheriting nothing it does not use', () => {
    // The `SignedInfo` case: the apex inherits `urn:outer` from its parent and uses none of it.
    const document = parseXml('<Outer xmlns:o="urn:outer"><Inner xmlns:i="urn:inner"><i:Leaf/></Inner></Outer>');
    const inner = childNamed(document, '', 'Inner');
    expect(canonicalizeExclusive(inner as XmlElement)).toBe(
      '<Inner><i:Leaf xmlns:i="urn:inner"></i:Leaf></Inner>',
    );
  });
});

// ---------------------------------------------------------------------------
// Signature verification
// ---------------------------------------------------------------------------

const { privateKey, publicKey } = generateKeyPairSync('rsa', { modulusLength: 2048 });

const PUBLIC_KEY_PEM = publicKey.export({ type: 'spki', format: 'pem' }).toString();

const DS = 'http://www.w3.org/2000/09/xmldsig#';

/**
 * Builds a signed document the way an IdP would, using this module's own canonical form.
 *
 * Circular for the "valid signature verifies" case, and deliberately so — see the file header. Its
 * real job is to produce a *correctly signed* document that the refusal cases can then damage in one
 * specific way each, so that what a test proves is "this particular tampering is caught" rather than
 * "something is wrong with this document".
 */
function signedDocument(options: {
  readonly assertionId?: string;
  readonly body?: string;
  readonly referenceUri?: string;
  readonly digestAlgorithm?: string;
  readonly signatureAlgorithm?: string;
  readonly canonicalizationAlgorithm?: string;
  readonly transforms?: readonly string[];
  /** Damage applied to the serialised XML *after* signing. */
  readonly tamper?: (xml: string) => string;
} = {}): { readonly xml: string; readonly assertionId: string } {
  const assertionId = options.assertionId ?? '_a1b2c3';
  const body = options.body ?? '<Subject>priya@example.com</Subject>';
  const digestAlgorithm = options.digestAlgorithm ?? 'http://www.w3.org/2001/04/xmlenc#sha256';
  const signatureAlgorithm =
    options.signatureAlgorithm ?? 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256';
  const canonicalizationAlgorithm =
    options.canonicalizationAlgorithm ?? 'http://www.w3.org/2001/10/xml-exc-c14n#';
  const transforms = options.transforms ?? [
    'http://www.w3.org/2000/09/xmldsig#enveloped-signature',
    'http://www.w3.org/2001/10/xml-exc-c14n#',
  ];

  // 1. Digest the assertion with no Signature inside it, exactly as the enveloped transform says.
  const unsigned = `<Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion" ID="${assertionId}">${body}</Assertion>`;
  const digest = createHashDigest(canonicalizeExclusive(parseXml(unsigned)));

  const signedInfo =
    `<ds:SignedInfo xmlns:ds="${DS}">` +
    `<ds:CanonicalizationMethod Algorithm="${canonicalizationAlgorithm}"></ds:CanonicalizationMethod>` +
    `<ds:SignatureMethod Algorithm="${signatureAlgorithm}"></ds:SignatureMethod>` +
    `<ds:Reference URI="${options.referenceUri ?? `#${assertionId}`}">` +
    `<ds:Transforms>${transforms.map((t) => `<ds:Transform Algorithm="${t}"></ds:Transform>`).join('')}</ds:Transforms>` +
    `<ds:DigestMethod Algorithm="${digestAlgorithm}"></ds:DigestMethod>` +
    `<ds:DigestValue>${digest}</ds:DigestValue>` +
    `</ds:Reference></ds:SignedInfo>`;

  // 2. Sign the canonical SignedInfo.
  const signer = createSign('RSA-SHA256');
  signer.update(canonicalizeExclusive(parseXml(signedInfo)), 'utf8');
  const signatureValue = signer.sign(privateKey, 'base64');

  const signature = `<ds:Signature xmlns:ds="${DS}">${signedInfo}<ds:SignatureValue>${signatureValue}</ds:SignatureValue></ds:Signature>`;
  const xml = `<Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion" ID="${assertionId}">${body}${signature}</Assertion>`;

  return { xml: options.tamper ? options.tamper(xml) : xml, assertionId };
}

function createHashDigest(canonical: string): string {
  // Local rather than imported so the test states its own expectation of the digest input.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { createHash } = require('node:crypto') as typeof import('node:crypto');
  return createHash('sha256').update(canonical, 'utf8').digest('base64');
}

const verify = (xml: string, certificate = PUBLIC_KEY_PEM) => {
  const document = parseXml(xml);
  return verifyXmlSignature({ document, signed: document, certificate });
};

describe('signature verification accepts a correctly signed assertion', () => {
  it('verifies the digest and the signature together', () => {
    // Circular by construction (see the header) — its value is as the control the cases below vary.
    expect(verify(signedDocument().xml)).toEqual({ ok: true });
  });
});

describe('signature verification refuses a tampered assertion', () => {
  it('refuses altered content, with the signature left intact', () => {
    // The signature still verifies over SignedInfo; the *digest* no longer matches the content. This
    // is the attack that matters, and the reason the digest is checked separately.
    const { xml } = signedDocument({
      tamper: (raw) => raw.replace('priya@example.com', 'attacker@example.com'),
    });

    expect(verify(xml)).toEqual({ ok: false, reason: 'digest_mismatch' });
  });

  it('refuses an added attribute, which changes the canonical form', () => {
    const { xml } = signedDocument({
      tamper: (raw) => raw.replace('<Subject>', '<Subject role="owner">'),
    });

    expect(verify(xml)).toEqual({ ok: false, reason: 'digest_mismatch' });
  });

  it('refuses a corrupted SignatureValue', () => {
    const { xml } = signedDocument({
      tamper: (raw) =>
        raw.replace(/<ds:SignatureValue>(.)/, (_match, first: string) =>
          `<ds:SignatureValue>${first === 'A' ? 'B' : 'A'}`,
        ),
    });

    expect(verify(xml)).toEqual({ ok: false, reason: 'bad_signature' });
  });

  it('refuses a signature made by a different key', () => {
    const other = generateKeyPairSync('rsa', { modulusLength: 2048 });
    const otherPem = other.publicKey.export({ type: 'spki', format: 'pem' }).toString();

    expect(verify(signedDocument().xml, otherPem)).toEqual({ ok: false, reason: 'bad_signature' });
  });
});

describe('signature verification refuses the wrapping attacks', () => {
  it('refuses a document where two elements carry the referenced id', () => {
    /**
     * The classic XML signature wrapping attack.
     *
     * The attacker keeps the legitimately signed assertion and adds a second element with the same
     * id holding their own claims. A verifier that resolved the reference to the *first* match would
     * confirm the signature while the application read the second.
     */
    const { xml, assertionId } = signedDocument();
    const wrapped = xml.replace(
      '<Subject>',
      `<Decoy ID="${assertionId}"><Subject>attacker@example.com</Subject></Decoy><Subject>`,
    );

    expect(verify(wrapped)).toEqual({ ok: false, reason: 'duplicate_id' });
  });

  it('refuses a signature that references an element other than the one being verified', () => {
    const { xml } = signedDocument({ referenceUri: '#somewhere-else' });

    expect(verify(xml)).toEqual({ ok: false, reason: 'reference_mismatch' });
  });

  it('refuses an empty reference URI, which would claim the whole document', () => {
    const { xml } = signedDocument({ referenceUri: '' });

    expect(verify(xml)).toEqual({ ok: false, reason: 'reference_mismatch' });
  });

  it('refuses a signature that is not a direct child of what it signs', () => {
    // Moved one level down. The signature is still present and still valid over its own SignedInfo,
    // so only the structural check catches this.
    const { xml } = signedDocument();
    const moved = xml
      .replace(/<ds:Signature[\s\S]*<\/ds:Signature>/, '')
      .replace('<Subject>', '<Wrapper>' + (xml.match(/<ds:Signature[\s\S]*<\/ds:Signature>/)?.[0] ?? '') + '</Wrapper><Subject>');

    expect(verify(moved)).toEqual({ ok: false, reason: 'signature_not_enveloped' });
  });

  it('refuses an assertion with no signature at all', () => {
    const document = parseXml('<Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion" ID="_x"><Subject>a</Subject></Assertion>');

    expect(verifyXmlSignature({ document, signed: document, certificate: PUBLIC_KEY_PEM })).toEqual({
      ok: false,
      reason: 'no_signature',
    });
  });
});

describe('signature verification refuses algorithms outside the profile', () => {
  it('refuses SHA-1 digests', () => {
    const { xml } = signedDocument({ digestAlgorithm: 'http://www.w3.org/2000/09/xmldsig#sha1' });

    expect(verify(xml)).toEqual({ ok: false, reason: 'unsupported_digest_algorithm' });
  });

  it('refuses RSA-SHA1 signatures', () => {
    const { xml } = signedDocument({
      signatureAlgorithm: 'http://www.w3.org/2000/09/xmldsig#rsa-sha1',
    });

    expect(verify(xml)).toEqual({ ok: false, reason: 'unsupported_signature_algorithm' });
  });

  it('refuses inclusive canonicalisation, which this module does not implement', () => {
    // Refusing is the only honest answer: pretending to verify inclusive c14n with an exclusive
    // implementation would compare a digest against bytes nobody produced.
    const { xml } = signedDocument({
      canonicalizationAlgorithm: 'http://www.w3.org/TR/2001/REC-xml-c14n-20010315',
    });

    expect(verify(xml)).toEqual({ ok: false, reason: 'unsupported_canonicalization' });
  });

  it('refuses an unknown transform rather than ignoring it', () => {
    const { xml } = signedDocument({
      transforms: [
        'http://www.w3.org/2000/09/xmldsig#enveloped-signature',
        'http://www.w3.org/TR/1999/REC-xslt-19991116',
      ],
    });

    expect(verify(xml)).toEqual({ ok: false, reason: 'unsupported_transforms' });
  });

  it('refuses a transform pipeline in the wrong order', () => {
    const { xml } = signedDocument({
      transforms: [
        'http://www.w3.org/2001/10/xml-exc-c14n#',
        'http://www.w3.org/2000/09/xmldsig#enveloped-signature',
      ],
    });

    expect(verify(xml)).toEqual({ ok: false, reason: 'unsupported_transforms' });
  });

  it('refuses an empty certificate', () => {
    expect(verify(signedDocument().xml, '   ')).toEqual({ ok: false, reason: 'bad_certificate' });
  });

  it('refuses a certificate that is not a key at all, rather than throwing', () => {
    expect(verify(signedDocument().xml, 'not-a-certificate')).toEqual({
      ok: false,
      reason: 'bad_certificate',
    });
  });
});

describe('findElementsById', () => {
  it('collects every match rather than the first, which is what makes duplicates visible', () => {
    const document = parseXml('<r><a ID="x"/><b Id="x"/><c id="x"/><d ID="y"/></r>');

    expect(findElementsById(document, 'x')).toHaveLength(3);
    expect(findElementsById(document, 'y')).toHaveLength(1);
    expect(findElementsById(document, 'z')).toHaveLength(0);
  });
});
